spring:
  application:
    name: TransactionService2
  
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  


server:
  port: 8084


